#include "Orchestra/OrchestraDialect.h"

#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/OpImplementation.h"

using namespace mlir;
using namespace orchestra;

//===----------------------------------------------------------------------===//
// Orchestra Dialect
//===----------------------------------------------------------------------===//

// Include the TableGen-generated dialect implementation.
#include "Orchestra/OrchestraOpsDialect.cpp.inc"

// Dialect initialization hook. This is where we register our operations.
void OrchestraDialect::initialize() {
  // The addOperations<>() call is generated by the .cpp.inc file above.
  // It takes a template pack of all operations to register.
  addOperations<
    // This macro expands to a comma-separated list of all operation
    // classes defined in the .td file.
    #define GET_OP_LIST
    #include "Orchestra/OrchestraOps.h.inc"
  >();
}

//===----------------------------------------------------------------------===//
// TableGen'd Op Definitions
//===----------------------------------------------------------------------===//

// This is the a crucial include that brings in the C++ definitions for
// all the operations. Without this, we would get linker errors.
#define GET_OP_CLASSES
#include "Orchestra/OrchestraOps.cpp.inc"
