#ifndef ORCHESTRA_ORCHESTRADIRECT_H
#define ORCHESTRA_ORCHESTRADIRECT_H

#include "mlir/IR/Dialect.h"

// This includes the C++ class declaration for the Orchestra dialect.
// It is generated by the TableGen utility from the `OrchestraDialect.td` file,
// which contains the high-level specification of the dialect.
#include "Orchestra/OrchestraDialect.h.inc"

#endif  // ORCHESTRA_ORCHESTRADIRECT_H
