#ifndef ORCHESTRA_ORCHESTRADIRECT_H
#define ORCHESTRA_ORCHESTRADIRECT_H

#include "mlir/IR/Dialect.h"

// This includes the C++ class declaration for the dialect,
// which is generated by TableGen from OrchestraOps.td.
#include "Orchestra/OrchestraOpsDialect.h.inc"

#endif // ORCHESTRA_ORCHESTRADIRECT_H
